kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.local:5000"]
    endpoint = ["http://kind-registry:5000"]

nodes:
- role: control-plane
  # limita recursos visibles al scheduler (≈2 vCPU / 2.5 Gi)
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: cpu=250m,memory=256Mi
- role: worker
  # limita recursos visibles al scheduler (≈2 vCPU / 5 Gi)
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: cpu=250m,memory=256Mi