# Versión compacta adaptada a kind (insecure‑tls)
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: metrics-server
  labels:
    k8s-app: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      labels:
        k8s-app: metrics-server
    spec:
      containers:
        - name: metrics-server
          image: k8s.gcr.io/metrics-server/metrics-server:v0.7.0
          args:
            - --kubelet-insecure-tls
            - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
          ports:
            - containerPort: 4443
              name: main-port
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1000
      nodeSelector:
        kubernetes.io/os: linux