apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-api-hpa
  namespace: tfg-iot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-api
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization        # ← NUEVO formato
        averageUtilization: 50   # 50 % de 100 m = 50 m
  behavior:                      # ← BLOQUE NUEVO
    scaleUp:
      stabilizationWindowSeconds: 30   # evita escalados ping-pong
      policies:
      - type: Percent
        value: 100          # x2 máx cada minuto
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50           # ÷2 máx cada minuto
        periodSeconds: 60
