apiVersion: 1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: tfg-iot
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: CrateDB
        type: postgres
        access: proxy
        url: cratedb:5432
        database: doc
        user: crate
        secureJsonData:
          password: default
        isDefault: true
        jsonData:
          sslmode: disable
          postgresVersion: 1200
