apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-api-ingress
  namespace: tfg-iot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: tfg.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: flask-api
                port:
                  number: 5000
