version: '3.3'

services:
  cratedb:
    image: crate:latest
    environment:
      - CRATE_HEAP_SIZE=${CRATE_HEAP_SIZE}
      - CRATE_NETWORK_HOST=0.0.0.0
    volumes:
      - cratedb_data:/data
    networks:
      - crate-net
    ports:
      - "4200:4200"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - cratedb
    networks:
      - crate-net
    volumes:
      - grafana-data:/var/lib/grafana

  flask-api:
    build: ../API 
    ports:
      - "5000:5000"
    depends_on:
      - cratedb
    networks:
      - crate-net
    volumes:
      - ../API:/app
    env_file:
      - .env

  data-generator:
    build: ../data_generator
    environment:
      - DISPLAY=host.docker.internal:0.0  # Para habilitar la interfaz gráfica
    depends_on:
      - flask-api
    networks:
      - crate-net
    volumes:
      - ../data_generator:/app
    env_file:
      - ../BD/.env

volumes:
  cratedb_data: {}
  grafana-data: {}

networks:
  crate-net:
    external: true